### PR TITLE
Displays an error message if an uploaded image is too large

### LINKED ISSUE #1634: Editor doesn't handle upload too large error
The 413 error returned by nginx when the 'request entity too large' isn't gracefully handled by the editor (it just eats the error).  The editor is expecting a json body and is getting nginx's standard error page instead.

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by jpeterson976**
Fixes #1634

Just shows a simple error message in the Choose Image modal if the user attempts to upload an image that's too large, so there's some kind of feedback for them as to what happened and it doesn't look like it just failed to upload.

### CODE REVIEW

**Review by maufcost — DISMISSED** [review]
Works pretty good to me! I tried with regular images (JPEGs, PNGs, and SVGs) and videos (MP4). Good job :)

**Review by FrenjaminBanklin — DISMISSED** [review]
Attempting to upload a huge .gif displayed the error appropriately.

Attempting to upload any non-supported filetype also displayed appropriately.

Looks good.

**Review by FrenjaminBanklin — APPROVED** [review]
Previous review still stands.

**Comment by FrenjaminBanklin** [comment]
Nothing really changed since retargeting this other than the original reviews being dismissed, so I'm going to go ahead and merge it.

**Pull request merged**
