### PR TITLE
Figures scale proportionally to height

### LINKED ISSUE #1533: Make figures scale proportionally when only height is set
Currently in figures if you set the size to custom, define the width but leave the height blank it will scale the image down proportionally. The same is not true for height - the image will distort since the height will remain fixed and the width will shrink. If possible, I think that setting only height should behave the same way as only setting width - the image should scale proportionally.

I am blanking on the HTML behavior for img but we may need to steal some code from IFrame as it handles proportional scaling.

### PR DESCRIPTION
**Pull request by jpeterson976**
Resolves #1533

### CODE REVIEW

**Review by zachberry — CHANGES_REQUESTED** [review]
This works great except for one case - If an image is given a height value and no width, which would cause the width of the image to proportionally expand past the available width, the image is distorted. As an example, upload an image and set the height to 3000px (leave the width blank).

Instead, the new width should still max out at the available width. So if a large height value is given which would cause the image to distort, we instead set the image to the maximum available width and don't honor the author's intended height value.

That's my initial thought on expected behavior, but I'm open to discussion on it.

**Comment by iturgeon** [comment]
I just want to say: weirdly, getting Figures to do exactly what we want at all times is surprisingly difficult.  I spent a lot of time on this - there's a lot of different situations given the various possible image sizes, size settings, and media queries.

**Comment by zachberry** [comment]
I came up with some test images to test this, I'm going to go ahead and add them here. Might be helpful for future features for images as well.

200x200
800x600
600x800
2000x200
200x2000
2000x2000

**Comment by zachberry** [comment]
I came up with a test document using the images above, here it is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ObojoboDraftDoc>
	<Module title="Image Test" id="ea2375e4-9906-4501-947a-eb61a90d3e10">
		<Content id="ec0762ff-bd66-4436-9d5b-89fae871f5cb">
			<Page title="200x200" id="2c4442ac-6b1a-4512-913e-58ea8da3eac4">
				<Heading headingLevel="1" id="6ad7be71-e428-4309-a7a8-9069aa15e483">
					<textGroup>
						<t align="left">Your Title Here</t>
					</textGroup>
				</Heading>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="small" id="a2739d1c-925f-4c32-b6d0-b5aec8041563">
					<textGroup>
						<t>Small</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="medium" id="29b83c4e-c664-4f1b-a74b-51c2774c5fa2">
					<textGroup>
						<t>Medium</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="large" id="b4af6d62-731e-42c9-bd88-097a552d5632">
					<textGroup>
						<t>Large</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="200" height="200" id="3b25f78d-682c-413b-9f84-b2d1aad5a445">
					<textGroup>
						<t>200x200</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="200" height="" id="d0624c20-44c1-4931-867f-83966f7b7394">
					<textGroup>
						<t>200x___</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="" height="200" id="3feb1952-ddee-4f82-9ed4-2f2a611c9a99">
					<textGroup>
						<t>___x200</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="" height="" id="55ff2003-7cff-46a3-b324-debab23219c9">
					<textGroup>
						<t>___x___</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="2000" height="2000" id="68bfe708-628f-4c46-a8c6-16c00f41067d">
					<textGroup>
						<t>2000x2000</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="2000" height="" id="13241239-1525-4793-a065-e2afb7d0bb86">
					<textGroup>
						<t>2000x___</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="" height="2000" id="d45ad922-6184-40be-9ce3-6590f164298b">
					<textGroup>
						<t>___x2000</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="600" height="200" id="e94dcf1e-18f2-4e11-8eeb-d9bc388e4f8a">
					<textGroup>
						<t>600x200</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="200" height="600" id="1261ffda-72a9-4023-8fb8-1701f455b9b0">
					<textGroup>
						<t>200x600</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="2000" height="200" id="a7e9d323-dc52-48b4-9947-5576f0ab9ca4">
					<textGroup>
						<t>2000x200</t>
					</textGroup>
				</Figure>
				<Figure url="7461254b-025f-4410-8d9d-ca17637542b1" size="custom" width="200" height="2000" id="331c8e50-d95d-488d-acae-10e04e412a7a">
					<textGroup>
						<t>200x2000</t>
					</textGroup>
				</Figure>
				<Text id="0bd01a20-d242-4e85-a657-5b73ba500d36">
					<textGroup>
						<t align="left" indent="0" hangingIndent="false">Your content here</t>
					</textGroup>
				</Text>
			</Page>
			<Page title="2000x2000" id="4c21c22b-dac3-42cd-8b77-0e317a1ae1c9">
				<Heading headingLevel="1" id="fd45c43a-379a-497c-a542-dfec3a0f0142">
					<textGroup>
						<t align="left">Your Title Here</t>
					</textGroup>
				</Heading>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="small" id="65d4329e-5f5a-4417-847b-de02e1ce9ba6">
					<textGroup>
						<t>Small</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="medium" id="dcaec44e-b389-407e-a831-c869f2e68867">
					<textGroup>
						<t>Medium</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="large" id="0f271d9d-956b-4537-aba1-3950d3f8f04d">
					<textGroup>
						<t>Large</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="200" height="200" id="434df878-7caa-4108-93bb-87a6fb8b8772">
					<textGroup>
						<t>200x200</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="200" height="" id="16319a6f-7657-4c0e-b4f1-4437f668af46">
					<textGroup>
						<t>200x___</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="" height="200" id="f5a39071-8f64-40ff-82f9-91d595322ca2">
					<textGroup>
						<t>___x200</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="" height="" id="9b53d109-fa6b-45f0-b20a-2874dfe87056">
					<textGroup>
						<t>___x___</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="2000" height="2000" id="1fd8cca4-a268-47db-b1c7-739716505977">
					<textGroup>
						<t>2000x2000</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="2000" height="" id="f732bf27-7f86-4f71-bdce-a937fe0daef8">
					<textGroup>
						<t>2000x___</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="" height="2000" id="519f3bf6-b4d7-47dd-9a0d-a7fe1baf0958">
					<textGroup>
						<t>___x2000</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="600" height="200" id="96624be9-f4cb-412a-925c-c3c0bd03fe99">
					<textGroup>
						<t>600x200</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="200" height="600" id="93fcb2e9-1174-4287-8f4d-b5d879c1895a">
					<textGroup>
						<t>200x600</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="2000" height="200" id="5b962f4f-1637-427a-91f2-d9355fc0df07">
					<textGroup>
						<t>2000x200</t>
					</textGroup>
				</Figure>
				<Figure url="c1057b6b-4019-46e2-94d0-3fca94dcbf97" size="custom" width="200" height="2000" id="149056ae-9e6d-4f04-b732-722bb284da79">
					<textGroup>
						<t>200x2000</t>
					</textGroup>
				</Figure>
				<Text id="54e2ebe8-09dc-4263-84f0-c4d15e2ccabe">
					<textGroup>
						<t align="left" indent="0" hangingIndent="false">Your content here</t>
					</textGroup>
				</Text>
			</Page>
			<Page title="2000x200" id="7a8ab4a7-a64c-4b60-b5fa-fef06f9b209f">
				<Heading headingLevel="1" id="f1050ac1-6da1-4882-acc8-1ea75d4da3f2">
					<textGroup>
						<t align="left">Your Title Here</t>
					</textGroup>
				</Heading>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="small" id="ad81ef1d-9fa4-4353-ab2b-5e86140655fe">
					<textGroup>
						<t>Small</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="medium" id="5f410224-4cb8-4dce-a077-d2e1bbcdaa16">
					<textGroup>
						<t>Medium</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="large" id="95a4a5db-5a9f-430b-beb1-99e55fcc7fb3">
					<textGroup>
						<t>Large</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="200" height="200" id="a5674579-fcc6-4ae4-8bc0-4067f1ee40c6">
					<textGroup>
						<t>200x200</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="200" height="" id="b0844748-7fbe-4777-8cf4-38f880901371">
					<textGroup>
						<t>200x___</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="" height="200" id="0dc32355-ce5a-4481-87fd-d50b1a01df9b">
					<textGroup>
						<t>___x200</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="" height="" id="40ac08a7-d3a2-473d-a653-05563d189a0a">
					<textGroup>
						<t>___x___</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="2000" height="2000" id="67d27e4e-1dfa-459d-a934-85428860f715">
					<textGroup>
						<t>2000x2000</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="2000" height="" id="fd068507-40d4-40d1-b1db-82ccada446db">
					<textGroup>
						<t>2000x___</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="" height="2000" id="7f78b7dd-a608-48a4-840b-74bbb4386f41">
					<textGroup>
						<t>___x2000</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="600" height="200" id="9f59f529-fa65-46a4-b9e2-434dd4646b3e">
					<textGroup>
						<t>600x200</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="200" height="600" id="ad0e4a54-f002-4d26-bda6-bb5ef01d6489">
					<textGroup>
						<t>200x600</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="2000" height="200" id="8b477aa7-80ab-4ff8-b396-31121b6bb049">
					<textGroup>
						<t>2000x200</t>
					</textGroup>
				</Figure>
				<Figure url="b1aaea7a-0a1e-497e-a5f9-d4acdb5a53a3" size="custom" width="200" height="2000" id="d5dd7ae2-937e-48b3-9406-a910395347d9">
					<textGroup>
						<t>200x2000</t>
					</textGroup>
				</Figure>
				<Text id="09e4f75c-850a-4595-b097-47378be36944">
					<textGroup>
						<t align="left" indent="0" hangingIndent="false">Your content here</t>
					</textGroup>
				</Text>
			</Page>
			<Page title="200x2000" id="5b3cdcbd-214a-47cc-b744-229f7b8a969d">
				<Heading headingLevel="1" id="4d0e2bef-25cf-4fb9-a906-26380bb1bd72">
					<textGroup>
						<t align="left">Your Title Here</t>
					</textGroup>
				</Heading>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="small" id="2c496405-a4a2-49d3-aded-f0a8f22223b9">
					<textGroup>
						<t>Small</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="medium" id="91aa95d5-885b-4c2e-aae0-07423b6e98a1">
					<textGroup>
						<t>Medium</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="large" id="bbbb8e3c-1650-4912-8401-65e233ca14db">
					<textGroup>
						<t>Large</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="200" height="200" id="a54aec68-ec1b-4610-99ab-ce078fa6e704">
					<textGroup>
						<t>200x200</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="200" height="" id="fe92afe6-4fa2-40cb-acf1-a214491eef34">
					<textGroup>
						<t>200x___</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="" height="200" id="6d606780-2e3f-4a18-9a64-de5347583e87">
					<textGroup>
						<t>___x200</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="" height="" id="194a206b-e15a-47d5-bf48-d45accbd161f">
					<textGroup>
						<t>___x___</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="2000" height="2000" id="6303f5d6-97b2-4a48-9a36-5cffb89664f3">
					<textGroup>
						<t>2000x2000</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="2000" height="" id="a54d98e8-23b5-44e4-981d-d29e6a159a3e">
					<textGroup>
						<t>2000x___</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="" height="2000" id="4f30dfd2-1426-40cf-b237-5e2b2959839f">
					<textGroup>
						<t>___x2000</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="600" height="200" id="231fb3e6-28c3-449d-9623-2e9cf6748264">
					<textGroup>
						<t>600x200</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="200" height="600" id="2f6e2095-1875-4f69-8a6f-698aa6e1614a">
					<textGroup>
						<t>200x600</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="2000" height="200" id="5e3bdbb9-a24c-43d0-a4dc-e344b26e7cb3">
					<textGroup>
						<t>2000x200</t>
					</textGroup>
				</Figure>
				<Figure url="40beb2d7-91cc-405f-9776-45e0217cdf03" size="custom" width="200" height="2000" id="d0bd73f6-02bf-465a-8d29-2c013b94a1f5">
					<textGroup>
						<t>200x2000</t>
					</textGroup>
				</Figure>
				<Text id="6e096045-b6e3-4640-8335-34642c45e6b1">
					<textGroup>
						<t align="left" indent="0" hangingIndent="false">Your content here</t>
					</textGroup>
				</Text>
			</Page>
			<Page title="800x600" id="61b9b906-2811-47ed-92f3-d5dc98bab523">
				<Heading headingLevel="1" id="e92b338c-f2b1-4a5e-b67d-0d006dfa44ec">
					<textGroup>
						<t align="left">Your Title Here</t>
					</textGroup>
				</Heading>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="small" id="2b9888cd-d234-49d2-a30e-64370bc06e35">
					<textGroup>
						<t>Small</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="medium" id="fb383b16-843b-4870-83f1-2e1773bfda1c">
					<textGroup>
						<t>Medium</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="large" id="a938e766-8f16-4781-9ae0-92fcb1a2ac4c">
					<textGroup>
						<t>Large</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="200" height="200" id="87223874-6fe1-41e1-8af3-05b3c3b5ceec">
					<textGroup>
						<t>200x200</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="200" height="" id="76170c82-e056-444d-adc8-88367b5bd096">
					<textGroup>
						<t>200x___</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="" height="200" id="1001ecde-3947-46d6-bf38-3f2b208421c4">
					<textGroup>
						<t>___x200</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="" height="" id="aa4cc9e2-fa8a-4ff5-ae28-04717d22f204">
					<textGroup>
						<t>___x___</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="2000" height="2000" id="bfdbc960-4348-4a53-8a32-7526bae6e6ff">
					<textGroup>
						<t>2000x2000</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="2000" height="" id="190840f6-aa91-4a31-8af3-d0e050e7bb57">
					<textGroup>
						<t>2000x___</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="" height="2000" id="624bde3a-da3d-45a5-919a-30886410d209">
					<textGroup>
						<t>___x2000</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="600" height="200" id="210e9385-cd8c-45ba-9040-8878c385b49c">
					<textGroup>
						<t>600x200</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="200" height="600" id="b75065b1-0879-4e21-b7bb-8a4971982306">
					<textGroup>
						<t>200x600</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="2000" height="200" id="6397c81d-02d0-4fd0-9507-0dcbee723574">
					<textGroup>
						<t>2000x200</t>
					</textGroup>
				</Figure>
				<Figure url="ab9304fb-d1b1-4d18-8633-72634dc286e1" size="custom" width="200" height="2000" id="89a37f71-7cea-4d2d-90f3-77bad7d4ac59">
					<textGroup>
						<t>200x2000</t>
					</textGroup>
				</Figure>
				<Text id="8206a77f-80ef-4c44-a1d5-d2affa6fd6ca">
					<textGroup>
						<t align="left" indent="0" hangingIndent="false">Your content here</t>
					</textGroup>
				</Text>
			</Page>
		</Content>
		<Assessment title="Assessment" review="never" attempts="3" id="my-assessment">
			<Page id="d0c48a4a-b041-4714-a44b-efca3bae6000">
				<Heading headingLevel="1" id="bde6f70f-42e2-491f-8caa-7b4de0a1b3ae">
					<textGroup>
						<t align="center">Assessment Intro Title</t>
					</textGroup>
				</Heading>
				<Text id="f36fb5b9-829d-4333-9d1c-dca656afe600">
					<textGroup>
						<t align="center">Some overview before starting the Assessment.</t>
					</textGroup>
				</Text>
				<Text id="dff48950-183e-4728-b60f-91fd6d66d2e6">
					<textGroup>
						<t align="center">You have {{assessment:attemptsRemaining}} attempts remaining.</t>
					</textGroup>
				</Text>
				<ActionButton id="c75e8170-7a92-46c8-ad36-31c8e68d9123">
					<textGroup>
						<t>Start Assessment</t>
					</textGroup>
					<triggers>
						<trigger type="onClick">
							<actions>
								<action type="assessment:startAttempt">
									<value id="my-assessment"/>
								</action>
							</actions>
						</trigger>
					</triggers>
				</ActionButton>
			</Page>
			<QuestionBank select="sequential" id="4aa00fa8-6cf0-4d39-ad92-f972615fc1ac">
				<Question id="84686c50-dc83-4f8e-bb69-ddce208d1e28">
					<Heading headingLevel="1" id="e9dae16b-1166-47bb-b6aa-57329afa24ea">
						<textGroup>
							<t>Your Question Here</t>
						</textGroup>
					</Heading>
					<Text id="47935cf8-e767-404a-b75e-131c7a9bae25">
						<textGroup>
							<t>More question text here.</t>
						</textGroup>
					</Text>
					<MCAssessment shuffle="false" responseType="pick-one" id="c1b66ce7-0fd6-408f-8fcb-181e9f002211">
						<MCChoice score="100" id="72a494a1-a09f-4645-8850-741dfb3e26f0">
							<MCAnswer id="238fba8f-3ab5-433e-9663-f9335d5ada46">
								<Text id="c8fffaae-f58e-455b-be41-568b6b1dafc5">
									<textGroup>
										<t>Correct answer</t>
									</textGroup>
								</Text>
							</MCAnswer>
						</MCChoice>
						<MCChoice score="0" id="7fe80ae3-6caf-4577-a583-e4bbf3f1de0b">
							<MCAnswer id="45ba914c-e930-45d4-830e-09eb69f5ac1a">
								<Text id="c5ecfa05-680b-4989-9e1f-1b8c797aea6d">
									<textGroup>
										<t>Incorrect answer</t>
									</textGroup>
								</Text>
							</MCAnswer>
						</MCChoice>
					</MCAssessment>
				</Question>
			</QuestionBank>
			<scoreActions>
				<scoreAction for="[0,100]">
					<Page id="d7f8d55b-9c84-4960-9b81-167e7bf8bed4">
						<Heading headingLevel="1" id="8dccd3ef-b2a0-41d3-a9d2-fe10ebd6789e">
							<textGroup>
								<t align="center">How did you do?</t>
							</textGroup>
						</Heading>
						<Text id="7f7b1031-9b76-4054-b594-5a9067a4dfbf">
							<textGroup>
								<t align="center">You have {{assessment:attemptsRemaining}} attempts remaining.</t>
							</textGroup>
						</Text>
						<ActionButton align="center" id="5349b1af-63ec-4dec-ae41-513ee10f2dc3">
							<textGroup>
								<t>Retry Assessment</t>
							</textGroup>
							<triggers>
								<trigger type="onClick">
									<actions>
										<action type="assessment:startAttempt">
											<value id="my-assessment"/>
										</action>
									</actions>
								</trigger>
							</triggers>
						</ActionButton>
					</Page>
				</scoreAction>
			</scoreActions>
			<triggers>
				<trigger type="onStartAttempt">
					<actions>
						<action type="nav:lock">
							<value/>
						</action>
					</actions>
				</trigger>
				<trigger type="onEndAttempt">
					<actions>
						<action type="nav:unlock">
							<value/>
						</action>
					</actions>
				</trigger>
			</triggers>
		</Assessment>
	</Module>
</ObojoboDraftDoc>
```

For reference, here are screenshots of that test object using those images. These are on essentially the master branch, so this represents the way figures work before this branch.

Each page uses one of the test images
1. 200x200
2. 2000x2000
3. 2000x200
4. 200x2000
5. 800x600

Each page has images with the following settings:

1. small
2. medium
3. large
4. custom (200x200)
5. custom (200x___)
6. custom (___x200)
7. custom (___x___)
8. custom (2000x2000)
9. custom (2000x___)
10. custom (___x2000)
11. custom (600x200)
12. custom (200x600)
13. custom (2000x200)
14. custom (200x2000)

Screen Shot 2021-02-22 at 3 34 52 PM
Screen Shot 2021-02-22 at 3 35 03 PM
Screen Shot 2021-02-22 at 3 35 11 PM
Screen Shot 2021-02-22 at 3 35 18 PM
Screen Shot 2021-02-22 at 3 35 25 PM
Screen Shot 2021-02-22 at 3 35 35 PM
Screen Shot 2021-02-22 at 3 35 42 PM
Screen Shot 2021-02-22 at 3 35 48 PM
Screen Shot 2021-02-22 at 3 35 55 PM
Screen Shot 2021-02-22 at 3 36 00 PM
Screen Shot 2021-02-22 at 3 36 07 PM
Screen Shot 2021-02-22 at 3 36 14 PM
Screen Shot 2021-02-22 at 3 36 21 PM
Screen Shot 2021-02-22 at 3 36 28 PM
Screen Shot 2021-02-22 at 3 36 34 PM
Screen Shot 2021-02-22 at 3 36 40 PM
Screen Shot 2021-02-22 at 3 36 47 PM
Screen Shot 2021-02-22 at 3 36 53 PM
Screen Shot 2021-02-22 at 3 36 58 PM
Screen Shot 2021-02-22 at 3 37 06 PM
Screen Shot 2021-02-22 at 3 37 19 PM
Screen Shot 2021-02-22 at 3 37 31 PM
Screen Shot 2021-02-22 at 3 37 42 PM
Screen Shot 2021-02-22 at 3 37 49 PM
Screen Shot 2021-02-22 at 3 37 54 PM
Screen Shot 2021-02-22 at 3 38 02 PM
Screen Shot 2021-02-22 at 3 38 12 PM
Screen Shot 2021-02-22 at 3 38 19 PM
Screen Shot 2021-02-22 at 3 38 25 PM
Screen Shot 2021-02-22 at 3 38 31 PM
Screen Shot 2021-02-22 at 3 38 36 PM
Screen Shot 2021-02-22 at 3 38 42 PM
Screen Shot 2021-02-22 at 3 38 47 PM
Screen Shot 2021-02-22 at 3 38 53 PM
Screen Shot 2021-02-22 at 3 38 59 PM
Screen Shot 2021-02-22 at 3 39 04 PM

**Review by iturgeon — APPROVED** [review]
tested really quick by changing hight and width props.  existing images in the tutorial looked fine.  Behaved as expected 👍

**Pull request closed without merging**
