### PR TITLE
Added justified alignment option

### LINKED ISSUE #1926: Add a 'Justified' alignment option.
Currently it's possible for text to be left-, center-, or right-aligned, but not [justified](https://www.w3schools.com/cssref/pr_text_text-align.ASP).

### PR DESCRIPTION
**Pull request by maufcost**
Fixes #1926

### CODE REVIEW

**Review by deundrewilliams — COMMENTED** [review]
Tested in each browser, the justification button in the menu works for all, but it looks like the keystroke (cmd+shift+J) only works in Chrome and Safari

**Comment by maufcost** [comment]
Thanks for pointing this out. I will investigate.

**Comment by SJJacques** [comment]
The button and command both work for me on all browsers. It only justifies on Chrome; Firefox and Safari change alignment but there's no difference between left align and justify.

**Comment by maufcost** [comment]
Everything seems to be working now on all major browsers (Chrome, Safari, and Firefox). The issue before seemed to be a `white-space` bug exclusively on Firefox that developers had faced before. It's fixed now. Let me know if anyone comes across any issues.

**Comment by SJJacques** [comment]
Tested it out and everything seems to work.

**Review by deundrewilliams — DISMISSED** [review]
Tested again and everything (menu button and keystroke) works in each browser

**Review by jpeterson976 — APPROVED** [review]
Both the button and the command work in all three browsers for me as well. LGTM

**Review by jpeterson976 — APPROVED** [review]
Re-approving after base change

**Review by SJJacques — APPROVED** [review]
Also approving after base change.

**Pull request merged**
