### PR TITLE
Puts user data in first column in assessments data grid

### LINKED ISSUE #1877: Move user data columns in assessment score data grid to be the first columns
This is based off some user feedback - seems like a reasonable change to me.

### PR DESCRIPTION
**Pull request by jpeterson976**
Resolves #1877

### CODE REVIEW

**Review by zachberry — CHANGES_REQUESTED** [review]
The original issue was badly worded, but could you also do this change for data-grid-attempts.jsx as well?

**Review by maufcost — DISMISSED** [review]
Sweet. User data is now on the first columns on both grids. LGTM!

**Review by zachberry — APPROVED** [review]
LGTM!

**Review by zachberry — APPROVED** [review]

**Review by maufcost — APPROVED** [review]
Still looking pretty good! Good job :)

**Pull request merged**
