### PR TITLE
made it so that removing your own access to a module calls onClose()

### PR DESCRIPTION
**Pull request by SJJacques**
Tested on Firefox, Chrome, and Safari; automated tests pass and coverage is met.

### CODE REVIEW

**Review by jpeterson976 — DISMISSED** [review]
Dialog properly closes. LGTM!

**Review by deundrewilliams — APPROVED** [review]
Tested in each browser and share dialog closed for each one

**Review by FrenjaminBanklin — APPROVED** [review]
Low impact and does the job. Good work.

**Review by jpeterson976 — APPROVED** [review]
Dialog still closes with new base branch, re-approving

**Review by maufcost — APPROVED** [review]
Nice. LGTM!

**Pull request merged**
