### PR TITLE
Add table caption to the editor and the viewer

### PR DESCRIPTION
**Pull request by vutoan1245**
Resolve: #1163

### CODE REVIEW

**Comment by iturgeon** [comment]
Status?  Ignoring conflicts, did qwertynerd97's items get taken care of @Thetwam ?

**Comment by Thetwam** [comment]
@iturgeon I think you meant @vutoan1245 ?

**Comment by vutoan1245** [comment]
@iturgeon I forgot to request a review. It should be ready.

**Comment by iturgeon** [comment]
Merge conflicts are a little more involved then a quick fix to fit into dev/12, I'm going to target this at dev/13 for now.

**Comment by iturgeon** [comment]
Ignoring this for now due to:

> Just ignore the table caption PR, I realized that it is 10 times simpler to make a standardized caption for multiple nodes.

@vutoan1245 feel free to close this pr if that means starting from scratch?

**Comment by zachberry** [comment]
Closing based on the comment above, but we can reopen if needed

**Pull request closed without merging**
