### PR TITLE
Upgrade Slate to 0.5x

### PR DESCRIPTION
**Pull request by qwertynerd97**
Upgrades to the latest version of Slate, and adds in some quality of life fixes
This also includes the changes from #1008

### CODE REVIEW

**Comment by zachberry** [comment]
I haven't dug into the code but I did hit on the editor for a bit, and so far I'm pretty happy - it feels way closer to expectations than the older version of Slate. I did find some things however - these either seem to be bugs or things that were outside my expectations of what would happen:

* [ ] - Pressing enter at the end of a heading should create a new text chunk rather than a new heading
* [ ] - Undo/Redo keyboard shortcuts don't seem to work
* [ ] - Adding a new Text element via the menu throws an error
* [ ] - You can shift+tab a list enough that it breaks and loses styling
* [ ] - Pressing enter on the last line of a list (when that last line is blank) should create (and move focus to) a new Text chunk
* [ ] - You can indent a list forever
* [ ] - Cursor not hidden when clicking on a break (I did some CSS hacks to get this working on the current editor)
* [ ] - In the Code chunk pressing tab should only indent the line when at the beginning of the line
* [ ] - Having multiple lines of text selected and pressing TAB should indent each line selected (rather than replace with a \t)
* [ ] - In Question you can click to the right of the 'Add Solution' button and a cursor will show up at the end of 'At Solution'
* [ ] - In Questions the 'Toggle Header' dialog for Tables overlaps too much of the table content at the bottom
* [ ] - Toolbar: Changing the alignment of some selected text, then attempting to type doesn't work. However using Bold (for example) then attempting to type does work fine.

(I made them a checkbox list but they're open for debate if you disagree).

I haven't tested copy/pasting yet. I also have some issues with the way list styles work, but I need to figure out exactly what those issues are, so I'll make a new comment.

**Comment by zachberry** [comment]
You can also hit me over the head and say this is outside the scope (and we can move to another issue), but I think it'd be nice to have a one-button way to preview the module. Mockup of having a preview button at the top right of the editor:

obo-preview

**Comment by zachberry** [comment]
Here's how I'm thinking the lists should work. The ListStyles class (I believe) should be able to handle all of these use cases:

* [ ] - Clicking on the bulleted or ordered list buttons on a list with one indent level should completely convert the list to that type (e.g. making a second indent item would maintain the list type)
* [ ] - Clicking on the bulleted or ordered list buttons on a list with more than one indent level should change the type of the selected indent levels only.
* [ ] - Clicking on the style list buttons for a list of the other type (e.g. Clicking on the uppercase letter style for a bulleted list) should perform the changes listed above
* [ ] - Clicking on the style list buttons should set the list type at the selected indent levels only to the selected style

**Comment by zachberry** [comment]
I'll try to show examples in text. I'll use the `|` character to represent a cursor and `[...]` to represent multiple character selection. (For bulleted lists I'll always use the `*` character here out of laziness, but in the actual application it should use the filled circle, hollow circle and square bullets as expected)

## Handling single-indent level lists:

```
* Te|xt
* Text
```

Click on the Numbered List button:

```
1. Te|xt
2. Text
```

Move cursor:

```
1. Text
2. |Text
```

Press tab:

```
1. Text
	a. |Text
```

> Note that the newly indented line is also numeric - that's because the whole list is now numeric.

## Handling multiple-level indent lists:

```
* Text
	* Te|xt
* Text
	* Text
```

Click on the Numbered List button:

```
* Text
	1. Te|xt
* Text
	1. Text
```

> Note that both items at the second indent level have been converted to numeric.

Move cursor to end, hit enter:

```
* Text
	1. Text
	2. |
* Text
	1. Text
```

Hit tab

```
* Text
	1. Text
		* |
* Text
	1. Text
```

> Note that the created item is a bulleted list item, not a numbered list item. That's because the list is still a bulleted list (but a few indent levels have been overridden to be numeric)

## Handling multiple-character selections

```
* Text
	* Te[xt
		* Te]xt
			* Text
```

Click on the Numbered List button

```
* Text
	a. Te[xt
		i. Te]xt
			* Text
```

> Note that the changed items start at `a`, not `1`. `a` is the default for a numbered list.

## Handling clicking on the style buttons

```
* Text
	* Te|xt
		* Text
	* Text
```

Click on the `1.` button

```
* Text
	1. Te|xt
		* Text
	2. Text
```

> Note that, by default, the selected item should be `a.`, but because `1.` was pressed it is set to 1.

Move cursor

```
* Te|xt
	1. Text
		* Text
	2. Text
```

Click on the Numbered List button

```
1. Te|xt
	1. Text
		* Text
	2. Text
```

> Note that there are now two `1.` items. The first item in the list by default is `1.` now that items at indent level 1 have been converted to a numeric list. In addition, the items at indent level 2 are also numeric but have been overridden to use the `1.` style.

Move cursor

```
1. Text
	1. Text
		* Text|
	2. Text
```

Press enter

```
1. Text
	1. Text
		* Text
		* |
	2. Text
```

Press tab

```
1. Text
	1. Text
		* Text
			* |
	2. Text
```

> Note that the newly created item is bulleted. That's because the list is still a bulleted list, just with some numeric overrides.

**Comment by zachberry** [comment]
We talked and decided the list things mentioned above were out of scope for this PR and they've been moved to another issue ( #1161 )

**Comment by iturgeon** [comment]
Double / triple clicking to select a full word / node sometimes expands into the next node.   I'm not sure if this is a side effect of our code or something happening in slate, but It is something I use a lot when editing text.



I noticed this when I didn't realize I was expanding selection to the code block after my heading.  I then changed the heading level to reduce it's size and it replaced the code block with a heading. THEN undo broke with 2 of these errors:
```
index.es.js:171 Uncaught TypeError: Cannot assign to read only property 'id' of object '#<Object>'
    at Object.editor.apply (page-editor.js:212)```

**Comment by iturgeon** [comment]
clicking insert Text node button throws:
```
Uncaught TypeError: Invalid attempt to destructure non-iterable instance
    at _nonIterableRest (slate.js:76)
    at _slicedToArray (slate.js:82)
    at slate.js:8428
    at Object.withoutNormalizing (slate.js:5804)
    at Object.insertNodes (slate.js:8408)
    at insertBlockAtEnd (editor-component.js:42)
    at onClick (insert-menu.js:155)
    at HTMLUnknownElement.callCallback (react-dom.development.js:356)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:405)
    at invokeGuardedCallback (react-dom.development.js:460)
```

**Comment by iturgeon** [comment]
ordered Lists sequences seem easy to break

**Comment by iturgeon** [comment]
clicking on a math equation node in the document WHILE the editor overlay for it is open produces an error that doesn't appear to have any side effects:

```
Uncaught Error: Cannot resolve a Slate point from DOM point: [object Text],1
    at Object.toSlatePoint (slate-react.js:2363)
    at Object.toSlateRange (slate-react.js:2408)
    at HTMLDocument.<anonymous> (slate-react.js:1436)
    at later (slate-react.js:35)
```

**Comment by FrenjaminBanklin** [comment]
Only just barely know what I'm doing myself, but played around with it a little.

Adding a button and then clicking anywhere while the 'edit triggers' tooltip box is open will randomly throw this error:
```
Uncaught Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (slate-react.js:2363)
    at Object.toSlateRange (slate-react.js:2409)
    at HTMLDocument.<anonymous> (slate-react.js:1436)
    at later (slate-react.js:35)
```

Editing the button's triggers and clicking the 'OK' button on the dialogue throws away all the changes and throws two errors:
```
Uncaught TypeError: Invalid value used as weak map key
...
react-dom.development.js:416 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
...
```
Not sure if it's intentional, but it's possible to select the text inside the button and apply other styles to it (bold, italic, strikethrough, monospace) or turn it into a link. 


The link inside the button causes some weird text behavior.

It's possible to get the editor into a weird state where everything disappears and nothing can be edited by adding a text node, removing every other node, emptying the text node, and then pressing the 'delete' key. Every key or click event afterwards throws the same
`
Uncaught Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
`
error.

**Comment by qwertynerd97** [comment]
Some of the cursor selection problems (ie cursor showing up on question solution button) seem to be managed by slate, and have to do with how Slate identifies DOM nodes.  I've gone through and fixed the cleanly cut problems, but a couple of buttons inside Question maintain cursor no matter how I tag them.
Similarly, inline input boxes like the ones in Math Equations have trouble with the focus being stolen by the editor.  There is a fix ready in the Slate codebase, and when they release it it should be fairly simple to upgrade.

**Comment by zachberry** [comment]
Starting to test it. If you create strikethrough text, then bold some of the strikethrough text the look doesn't change. However if you save and preview then you do see the bold text in the viewer.

**Comment by iturgeon** [comment]
note - somewhere this pr accidentally added a bunch of stuff from the compiled folder.

I used bfg to clean them out, but that results in a diverged history: It's here now: https://github.com/iturgeon/Obojobo/tree/feature/upgrade-slate-52-remove-compiled

the current head of this branch when I cleaned it was 62231ad.

If you want to use my fixes, you'd have to force push to this branch to update it :)

Secondary note, it looks like zach /issue/1206-inline-latex-previews uses this branch as it's base, so it'd have to be updated too :(

**Pull request merged**
