### PR TITLE
Created rubric modal

### LINKED ISSUE #1650: Move Assessment Rubric to a Modal
Based on issues implementing #1539 (and in general with the difficulty to get Slate-controlled text and regular inputs to play nicely together, I think it would be best if we move the assessment rubric content into its own modal.

### PR DESCRIPTION
**Pull request by maufcost**
Created the rubric modal. To open it, go to a module's assessment page and scroll down to where the old rubric used to be. There, you will find a button to edit the assessment's rubric.

I am not completely sure about the new rubric design though. It feels a little bit cluttered. A few ideas:
- Perhaps we could slightly reduce the font-size
- Decrease the modal's overall padding. 
- Create separate sections for each part of the modal (to pass, passing, failing) separating them by greater margins with a very light grey/purple color for each section's background-color to modularize each section and make it easier to see all the information and options. (my favorite)

Any thoughts? :)

Fixes #1650

### CODE REVIEW

**Review by zachberry — CHANGES_REQUESTED** [review]
Good work so far! This should make editing this modal a lot less painful. I haven't reviewed the code yet, just played with it in the viewer.

I do agree it looks cluttered. Additionally if the browser window gets smaller a lot of the radio buttons don't line up anymore with the text, the text ends up on a new line. If you're interested in pursuing your favorite option I suggest mocking it up first so you don't get too in the weeds before we finalize it, but I'm all for changing the look - I'm not tied to the existing look at all. For some specific ideas on design - I think there's not enough padding, everything is too cramped. Also the Pass Fail Rules section perhaps could have smaller font, since it's a lot of rather big font. Separating the different sections like you're talking about would greatly help too.

I also think a summary could be put next to the button that launches the modal (for example it could say "Assessment scored by the highest attempt score" or "Assessment scored based on a threshold score of x%" based on which option they have selected) so they don't need to open the dialog to remember what setting they have. They'd still have to open it to see all the specifics of course. I'm also not tied to those specific wordings, it was the first thing that I thought of.

Last, when you convert the document to XML, if you have a rubric, you get `showModProperties` as an attribute - that should be removed, and shouldn't show up in the XML.

**Comment by maufcost** [comment]
Nice! We're on the same page then :) I am going to start working on a new mock-up and post it here soon.

**Comment by maufcost** [comment]
Here are some mock-ups I am toying with.

It's a blend of our current assessment page design and the new iframe chunk mock-up that Zac did. Also, on the last mock-up I added a new "description" that is shorter than the current one and that pretty much covers what the rubric can do for authors:

rubric-modal-mockup
rubric-modal-mockup-2
rubric-modal-mockup-3
rubric-modal-mockup-4

**Comment by zachberry** [comment]
@maufcost Looks great! A big improvement, I say go for it!

**Comment by maufcost** [comment]
Changes include:
- New rubric design
- New and shorter description on the title
- Removed `showModProperties` from the XML and JSON editors

If you would like to green light that rubric summary idea on this same PR, I've had a few thoughts:
1) We could add that question mark "hover-only button" next to the button that opens the rubric modal (very similar to the question mark button on the numeric branch).
rubric-summary
Screen Shot 2021-04-21 at 10 33 56 AM
2) We could just generate a quick, short, and "uncluttering" summary underneath the button that opens the modal.

**Comment by zachberry** [comment]
> Changes include:
> 
> * New rubric design
> * New and shorter description on the title
> * Removed `showModProperties` from the XML and JSON editors
> 
> If you would like to green light that rubric summary idea on this same PR, I've had a few thoughts:
> 
> 1. We could add that question mark "hover-only button" next to the button that opens the rubric modal (very similar to the question mark button on the numeric branch).
>    rubric-summary
>    Screen Shot 2021-04-21 at 10 33 56 AM
> 2. We could just generate a quick, short, and "uncluttering" summary underneath the button that opens the modal.

I haven't re-reviewed this yet, but I think the (?) button could work. It's the more-info-button.js. If we go with (?) I'd like it to give you a full summary with all the details however. I think it could fit in a similar size as the numeric one hopefully.

**Review by jpeterson976 — APPROVED** [review]
LGTM - tested in the editor and skimmed over the code. The new modal looks great, I think this design is much cleaner than the original. I agree about the more info button too, I think it could be good to add. Approving for now, if the button ends up being added in this PR I'll re-review.

**Review by zachberry — CHANGES_REQUESTED** [review]
A huge improvement, good work. I do have a few nit picky tweaks to add - Adds some spacing between the radio buttons and their labels, ensures the content is aligned with the line separator and gives the pass-fail section a smaller font so it doesn't take so much space. Thoughts?

```css
input[type='radio'] {
		margin-left: 0;
		margin-right: 0.5em;
	}
	label {
		display: flex;
		align-items: center;
	}
	.pass-fail {
		padding: 1em 0;
		font-size: 0.9em;
	}
	.assessment-score {
		padding: 1em 0;
	}
	.pass-fail legend {
		margin-bottom: 1em;
	}
```

**Comment by maufcost** [comment]
Agreed! I just pushed the new subtle design changes (looks a lot better).

**Review by jpeterson976 — APPROVED** [review]
Agree that it looks even better, still works great. Re-approved!

**Review by zachberry — CHANGES_REQUESTED** [review]
I found one final thing - If you update the number of attempts the Mod sliders don't seem to update. For example, if you have the attempts set to 10 and move the sliders it'll notch from 1, 2, ..., 9, 10, then $last_attempt (works great). But if you change the number of attempts to 5 and go back to the mods they'll still increment from 1 to 10, then $last_attempt (instead of 1, 2, ..., 4, 5, then $last_attempt).

If we can't fix in time I'd still like to get the updates in this release and fix next release.

**Comment by maufcost** [comment]
After pulling all the new changes from dev/20 and merging it with this rubric modal branch, I came across some lint issues locally. Apparently, all tests/snaphots are passing here. Let me know if you would like me to change anything :)

**Review by zachberry — APPROVED** [review]
Now that the Rubric is in its own modal we should be able to no longer build it out as a Slate node. That should help us simplify a lot of code. Additionally, we should be able to pass the Assessment data to the react component rather that having to find it via the new Editor Util method. That said, I think this is worth adding in now, and we can handle the refactor afterwards.

**Pull request merged**
