### PR TITLE
Repository Stage 1

### PR DESCRIPTION
**Pull request by iturgeon**
Modifies many aspects of Obojobo to add the first functionality needed in the repository:

1. A dashboard interface to serve as the home for authors
2. A public library needed to share modules easily
3. An upgrade to the picker interface to expose the public library modules

So many changes...

* [x]  obojobo-modules  can now register their own client scripts to run through webpack
* [x] obo modules can now provide their own db migrations using a modified obojobo-migration script that proxies to db-migrate
* [x] obojobo-repository module added
* [x] Adds server side events to allow modules to hook into things that occur in other modules.  
* [x] Adds react server side rendering for obojobo-repository
* [x] Removes module list/sidebar from xml editor
* [x] Adds redux and react-redux for use in obojobo-repository
* [x] Adds dashboard page
* [x] Adds ability to share editing rights to a module
* [x] Adds table to store modules in folders (though not implemented in api / gui)
* [x] Adds public page for each module
* [x] Adds public page for module library
* [x] Enables Public library in lti resource picker interface
* [x] Updates styles of lti resource picker UI
* [x] Moves picker code into obojobo-module-selector module
* [ ] security - make sure the user has perms to do things in the new api end points
* [x] add author and 3 editors, last edit date to module page
* [x] add menu to module edit page if possible
* [x] edit menu buttons - use darker over purple for buttons
* [x] close buttons - use correct glyph
* [x] dashboard - search more visible (to the right?)
* [x] remove main menu search
* [ ] rename old editor
* [ ] find a way to get the play/embed url
* [ ] share dialog heading should include 'editors'
* [x] new module button - pop a dialog with xml editor, visual editor, or tutorial as options
* [ ] preview button in new editor
* [x] Add new npm modules to Travis pipeline
* [ ] Make sure dep tree for obojobo-express really includes / expludes everything it should
* [ ] Investigate adding caliper events for repository actions
* [x] pull `express-react-views` out of the source, fork it if necessary
* [ ] tests for everything new
* [ ] sharing will create problems.  add a warning dialog before editing (or saving?) that warns people about the repercussions of updating a module if it has scores (maybe show them stats about the past uses of that module)
* [x] Add a button to download the raw xml/json #893 893
* [x] Nicer 401 page (logout from dashboard shows not authorized)
* [x] Nicer 404 page
* [x] Nicer 500 page

### CODE REVIEW

**Comment by iturgeon** [comment]
## Screen shots of LTI Resource Selection interface


Updated resource selection page.   Community Collection is now active and the colors/fonts/sizes updated.

Screen Shot 2019-06-27 at 4 14 22 PM

Select a module interface (Coummunity) has been cleaned and polished. Search gets center stage and the action buttons are aligned along the left side with preview links under them.  New Module button rests at the bottom.

Screen Shot 2019-06-27 at 4 18 27 PM

Select a module interface (Personal Library) matches the updates but has it's own color scheme

Screen Shot 2019-07-15 at 7 38 24 PM

**Comment by iturgeon** [comment]
Progress update screen shots

# Dashboard

For now, this is where you'll be redirected to when clicking on the LTI course nav.  If you're logged in, you can visit this page by by clicking on dashboard next to your name in the header.

Screen Shot 2019-08-15 at 1 57 56 PM

## Module Sharing

You can add multiple "owners" to a module.  There is no nuance to what sort of access they have, they'll be able to edit and delete your module.

### List of owners

Screen Shot 2019-08-15 at 1 58 14 PM

### Searching for people to share with

Screen Shot 2019-08-15 at 2 25 30 PM


# Library

The library will eventually be the page where you shop for modules.  In the beginning it'll show one "Collection" named "Community Collection" to match the name in the picker.  We should put a module in here by default (I'm thinking the Visual Editor Tutorial).  I don't currently know how someone will preview these OR create a copy for themselves.

Screen Shot 2019-08-15 at 2 24 40 PM

# Module Page

This is a placeholder for a more evolved page.  Current idea is we can put some help here on how to use this module in your course.

Screen Shot 2019-08-15 at 1 58 02 PM

**Comment by zachberry** [comment]
A few tweaks:

obo-ian-dashboard-mockups

obo-ian-dashboard-mockups2

obo-ian-dashboard-mockup3

**Comment by iturgeon** [comment]
This PR is replaced by #989

**Pull request closed without merging**
