### PR TITLE
Added past and current (some upcoming) contributors to the readme.

### PR DESCRIPTION
**Pull request by FrenjaminBanklin**
See https://github.com/FrenjaminBanklin/Obojobo/tree/feature/readme-contributors.

### CODE REVIEW

**Comment by FrenjaminBanklin** [comment]
I'd thought about dropping down to HTML on the first go-through, but the single-line-per-person Markdown solution was too good to pass up.

HTML is probably more predictable and error-proof in the long run, though. Will edit.

**Comment by zachberry** [comment]
@FrenjaminBanklin Totally fair & valid - I just wasn't super happy with having the text and image on the same line and I think the tradeoff here is worth it.

**Comment by iturgeon** [comment]
Screen Shot 2020-03-16 at 5 15 28 PM

**Comment by zachberry** [comment]
@iturgeon I did toy with a table making a grid, it's just that editing it would be a little bit of a pain.

Some example HTML:

```html
<table style="list-style-type:none; padding:0;">
	<tr>
		<td>
			<center>
				<a href="https://github.com/FrenjaminBanklin"
				><img
					width="100"
					height="100"
					src="https://avatars3.githubusercontent.com/u/7400747?s=100&v=4"
				/><br />Cameron Long Name Guy</a>
			</center>
		</td>
		<td>
			<center>
				<a href="https://github.com/FrenjaminBanklin"
				><img
					width="100"
					height="100"
					src="https://avatars3.githubusercontent.com/u/1275983?s=100&v=4"
				/><br />Scribbledip Jones</a>
			</center>
		</td>
	</tr>
</table>
```

Resulting in:

image

**Comment by zachberry** [comment]
I think we're closing this in favor of using a solution with https://github.com/all-contributors/all-contributors-bot

**Pull request closed without merging**
