### PR TITLE
Implemented Phase 2 for Obo Stats

### LINKED ISSUE #1869: Assessment Stats Dialog Phase 2
This is a follow up to work done on #1864 . There are some refactors and improvements still to do to the assessment stats feature:

* Merge AssessmentStatsSearchControls and AssessmentStatsFilterControls into one component, and have all filtering happen there
* Change search by text input to a hybrid text-input/select, which shows all of the possible values
* Change First / Last name to a single field, which searches both fields
* Set the min date of the date range inputs to the first day of the earliest record

### PR DESCRIPTION
**Pull request by maufcost**
Fixes #1869

### CODE REVIEW

**Comment by maufcost** [comment]
Everything is pretty much done. The only thing left now is the hybrid text-input/select. I will be doing that from scratch since it may be a more lightweight version of the library we were discussing earlier.

Also, after spending a couple more hours with `obo-stats`, the debouncing kept throwing me off (sometimes I didn't know if it was actually debouncing or if the page had somehow broken on the background because everything was static). I thought about adding a subtle spinner (just like the one I added for bulk operations in the dashboard) when we are debouncing - something that says to users: "Hey, I'm processing your request." Quick mockup is below. Thoughts?

obo

**Comment by maufcost** [comment]
Sneak peak at our new hybrid input/select component:
obo

**Comment by zachberry** [comment]
> Everything is pretty much done. The only thing left now is the hybrid text-input/select. I will be doing that from scratch since it may be a more lightweight version of the library we were discussing earlier.
> 
> Also, after spending a couple more hours with `obo-stats`, the debouncing kept throwing me off (sometimes I didn't know if it was actually debouncing or if the page had somehow broken on the background because everything was static). I thought about adding a subtle spinner (just like the one I added for bulk operations in the dashboard) when we are debouncing - something that says to users: "Hey, I'm processing your request." Quick mockup is below. Thoughts?
> 
> obo

I like that mockup, I say make it so

**Comment by maufcost** [comment]
The hybrid input select is implemented. Working on the loading indicator when debouncing happens now.

**Review by FrenjaminBanklin — APPROVED** [review]
This looks good and seems to be working well.

**Comment by FrenjaminBanklin** [comment]
This is pretty much ready to go. I can approve the majority of it, but since I also contributed it should probably get somebody else's eyes on it as well.

**Review by RachelDau — DISMISSED** [review]
this looks good to me, obo stats seems to be working well

**Comment by FrenjaminBanklin** [comment]
This has been reviewed by multiple people before, and it looks like everything is passing and working properly after modernizing it from the current dev branch. I'm going to go ahead and call it good.

**Pull request merged**
