### PR TITLE
Fixes input box weirdness for numeric questions w/ large units text

### LINKED ISSUE #1826: Numeric questions input box weird when units text is large
Likely not a common case, but we should have a max-height defined for the text input on numeric questions - See this example:

image

### PR DESCRIPTION
**Pull request by jpeterson976**
Resolves #1826

### CODE REVIEW

**Review by zachberry — CHANGES_REQUESTED** [review]
One final change, would like the checkmark or X to also be centered, seen here:

image

**Review by zachberry — CHANGES_REQUESTED** [review]
I found an issue when feedback is involved:

image

Otherwise, I tested various examples of both types of questions, both with and without feedback and with and without lots of text and all other cases look good.

**Comment by jpeterson976** [comment]
I noticed that the review flags when you click "Reveal Answer" were also not aligned properly, so I fixed that as well. I added some adjustments to the more info button for smaller screen sizes too, since it was hidden by the input box at sub-tablet sizes.

**Review by zachberry — APPROVED** [review]
I tested this with numeric and MC questions, both in practice and assessment, at all mobile sizes, and tested with ChromeVox, and found no issues - looks great!

**Review by maufcost — COMMENTED** [review]
Ignore this comment (Was supposed to be a review...) (Review below)

**Review by maufcost — APPROVED** [review]
LGTM! Tested with the same tools and sizes as Zac above ^ Good job!

**Pull request merged**
